= Go Asciidoc Document Generator
:author_name: Mario Toffia
:author: {author_name}
:author_email: mario.toffia@xy.net
:email: {author_email}
:source-highlighter: highlightjs
:icons: font
:imagesdir: ../meta/assets
:homepage: https://github.com/mariotoffia/goasciidoc
:kroki-default-format: svg
:doctype: book

== Package github.com/mariotoffia/goasciidoc

package main contains the one and only binary to run goasciidoc

=== Imports
[source, go]
----
import (
    _ "embed"
    "fmt"
    "os"
    "strings"
    "testing"
    "github.com/alexflint/go-arg"
    "github.com/mariotoffia/goasciidoc/asciidoc"
    "github.com/mariotoffia/goasciidoc/goparser"
    "github.com/stretchr/testify/assert"
    "io/ioutil"
    "path/filepath"
)
----

== Structs



== Variables



















== Functions









=== TestOverridePackageTemplate
[source, go]
----
func TestOverridePackageTemplate(t *testing.T)
----








=== TestTemplateDir
[source, go]
----
func TestTemplateDir(t *testing.T)
----








=== TestNonExported
[source, go]
----
func TestNonExported(t *testing.T)
----








=== TestParseHighlighter
[source, go]
----
func TestParseHighlighter(t *testing.T)
----









== Package github.com/mariotoffia/goasciidoc/asciidoc



=== Imports
[source, go]
----
import (
    "bytes"
    "fmt"
    "html"
    "io"
    "os"
    "path"
    "regexp"
    "strings"
    "testing"
    "encoding/json"
    "github.com/mariotoffia/goasciidoc/goparser"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    htmltemplate "html/template"
    "io/ioutil"
    "os/user"
    "path/filepath"
    "text/tabwriter"
    texttemplate "text/template"
)
----

== Structs

[[github-com-mariotoffia-goasciidoc-asciidoc-SignatureDoc]]

=== SignatureDoc
[source, go]
----
type SignatureDoc struct {
    Raw         string
    Kind        SignatureKind
    Segments    []SignatureSegment
}
----



==== Undocumented


[cols="1,1,1",options="header"]
|===
|Field |Type |Tag
|`Raw`|`string`|
|`Kind`|`SignatureKind`|
|`Segments`|`[]SignatureSegment`|
|===



[[github-com-mariotoffia-goasciidoc-asciidoc-SignatureSegment]]

=== SignatureSegment
[source, go]
----
type SignatureSegment struct {
    Kind       SignatureSegmentKind
    Content    htmltemplate.HTML
}
----



==== Undocumented


[cols="1,1,1",options="header"]
|===
|Field |Type |Tag
|`Kind`|`SignatureSegmentKind`|
|`Content`|`htmltemplate.HTML`|
|===



[[github-com-mariotoffia-goasciidoc-asciidoc-SignatureHighlightToken]]

=== SignatureHighlightToken
[source, go]
----
type SignatureHighlightToken struct {
    Class      string
    Content    htmltemplate.HTML
}
----



==== Undocumented


[cols="1,1,1",options="header"]
|===
|Field |Type |Tag
|`Class`|`string`|
|`Content`|`htmltemplate.HTML`|
|===



[[github-com-mariotoffia-goasciidoc-asciidoc-SignatureHighlightBlock]]

=== SignatureHighlightBlock
[source, go]
----
type SignatureHighlightBlock struct {
    WrapperClass    string
    Tokens          []SignatureHighlightToken
}
----



==== Undocumented


[cols="1,1,1",options="header"]
|===
|Field |Type |Tag
|`WrapperClass`|`string`|
|`Tokens`|`[]SignatureHighlightToken`|
|===



[[github-com-mariotoffia-goasciidoc-asciidoc-Producer]]

=== Producer
[source, go]
----
type Producer struct {
}
----

Producer parses go code and produces asciidoc documentation.




==== Receivers

===== Debug
[source, go]
----
func (p *Producer) Debug(enabled bool) *Producer
----
Debug toggles debug logging to stdout.


===== StdOut
[source, go]
----
func (p *Producer) StdOut() *Producer
----
StdOut writes to stdout instead onto filesystem.


===== EnableMacro
[source, go]
----
func (p *Producer) EnableMacro() *Producer
----
EnableMacro will enable the substitution of _goasciidoc_ custom macros.

A _goasciidoc_ macro is on the following form _${gad:macro-name[:...]}_ footnote:[goad stands for goasciidoc].


===== NonExported
[source, go]
----
func (p *Producer) NonExported() *Producer
----
NonExported will set renderer to render all Symbols both
exported and non exported. By default only exported symbols
are rendered.


===== Writer
[source, go]
----
func (p *Producer) Writer(w io.Writer) *Producer
----
Writer sets a custom writer where *everything* gets written to.


===== PackageDoc
[source, go]
----
func (p *Producer) PackageDoc(filepath ...string) *Producer
----
PackageDoc adds a relative, each package, filepath to search for overview package asciidoc.

For example _design/package.adoc will make goasciidoc to search relative each package path
for this particular folder and file.


===== OverrideFilePath
[source, go]
----
func (p *Producer) OverrideFilePath(name string, path string) *Producer
----
OverrideFilePath will use another template instead of a built-in default
for the particular name (see TemplateType for valid template names)
This is loaded from the in param path.


===== Override
[source, go]
----
func (p *Producer) Override(name string, template string) *Producer
----
Override will use another template instead of a built-in default
for the particular name (see TemplateType for valid template names)


===== Outfile
[source, go]
----
func (p *Producer) Outfile(path string) *Producer
----
Outfile sets a file to write to


===== NoIndex
[source, go]
----
func (p *Producer) NoIndex() *Producer
----
NoIndex specifies that the generated asciidoctor document will not have
a index header. This is good for inclusion where a header is already present.


===== NoToc
[source, go]
----
func (p *Producer) NoToc() *Producer
----
NoToc disables the table of contents if index is enabled. Default
is when index is enabled a table of contents is produced.


===== IndexConfig
[source, go]
----
func (p *Producer) IndexConfig(overrides string) *Producer
----
IndexConfig will configures using SON properties and hence it
will override the default IndexConfig configuration. If no override,
just pass an empty string.


===== Module
[source, go]
----
func (p *Producer) Module(path string) *Producer
----
Module directs the producer to pick up module from path.

path may be a directory or a full path to go.mod. If "" it
will use current directory.


===== TypeLinks
[source, go]
----
func (p *Producer) TypeLinks(mode TypeLinkMode) *Producer
----
TypeLinks configures how type references are rendered inside the generated documentation.


===== Concatenation
[source, go]
----
func (p *Producer) Concatenation(mode goparser.DocConcatenationMode) *Producer
----
Concatenation configures how doc comments split by blank lines are combined.


===== SignatureStyle
[source, go]
----
func (p *Producer) SignatureStyle(style string) *Producer
----
SignatureStyle controls how signatures are rendered (e.g. "goasciidoc", "source").


===== Highlighter
[source, go]
----
func (p *Producer) Highlighter(name string) *Producer
----
Highlighter controls which source highlighter attribute is emitted in the index header.


===== RenderOptions
[source, go]
----
func (p *Producer) RenderOptions(opts map[string]bool) *Producer
----
RenderOptions controls what examples to render for structs (struct-json, struct-yaml).


===== Include
[source, go]
----
func (p *Producer) Include(path ...string) *Producer
----
Include adds one or more directory or files in any combination. The producer
will sort out which are directories and which are filepaths.

If filepath, it will not do any type of checking and will blindly think it is a
valid go file.


===== IncludeTest
[source, go]
----
func (p *Producer) IncludeTest() *Producer
----
IncludeTest will create documentation for test files as well.


===== IncludeInternal
[source, go]
----
func (p *Producer) IncludeInternal() *Producer
----
IncludeInternal will include internal folder source files.


===== IncludeUnderScoreDirectories
[source, go]
----
func (p *Producer) IncludeUnderScoreDirectories() *Producer
----
IncludeUnderScoreDirectories will include files that resides below
directories starting with underscore.


===== CreateTemplateWithOverrides
[source, go]
----
func (p *Producer) CreateTemplateWithOverrides() *Template
----
CreateTemplateWithOverrides creates a new instance of _Template_
and add the possible _Provider.overrides_ into it.


===== Generate
[source, go]
----
func (p *Producer) Generate()
----
Generate will execute the generation of the documentation




[[github-com-mariotoffia-goasciidoc-asciidoc-TemplateAndText]]

=== TemplateAndText
[source, go]
----
type TemplateAndText struct {
    Text        string
    Template    *texttemplate.Template
}
----

TemplateAndText is a wrapper of _template.Template_
but also includes the original text representation
of the template and not just the parsed tree.



==== Text string


Text is the actual template that got parsed by _template.Template_.


==== Template *link:https://pkg.go.dev/text/template#Template[texttemplate.Template]


Template is the instance of the parsed _Text_ including functions.





[[github-com-mariotoffia-goasciidoc-asciidoc-Template]]

=== Template
[source, go]
----
type Template struct {
    Templates    map[string]*TemplateAndText
}
----

Template is handling all templates and actions
to perform.



==== Templates map[string]*<<github-com-mariotoffia-goasciidoc-asciidoc-TemplateAndText,TemplateAndText>>


Templates to use when rendering documentation



==== Receivers

===== NewContext
[source, go]
----
func (t *Template) NewContext(f *goparser.GoFile) *TemplateContext
----
NewContext creates a new context to be used for rendering.


===== NewContextWithConfig
[source, go]
----
func (t *Template) NewContextWithConfig(f *goparser.GoFile, p *goparser.GoPackage, config *TemplateContextConfig) *TemplateContext
----
NewContextWithConfig creates a new context with configuration.

If configuration is nil, it will use default configuration.




[[github-com-mariotoffia-goasciidoc-asciidoc-TemplateContext]]

=== TemplateContext
[source, go]
----
type TemplateContext struct {
    File               *goparser.GoFile
    Package            *goparser.GoPackage
    Module             *goparser.GoModule
    Struct             *goparser.GoStruct
    Function           *goparser.GoStructMethod
    Interface          *goparser.GoInterface
    TypeDefVar         *goparser.GoCustomType
    TypeDefFunc        *goparser.GoMethod
    VarAssignment      *goparser.GoAssignment
    ConstAssignment    *goparser.GoAssignment
    Config             *TemplateContextConfig
    Index              *IndexConfig
    Receiver           []*goparser.GoStructMethod
    Docs               map[string]string
}
----

TemplateContext is a context that may be used to render
a GoFile. Depending on the template, different fields are
populated in this struct.



==== File *<<github-com-mariotoffia-goasciidoc-goparser-GoFile,goparser.GoFile>>


File is the complete file. This property is always present.

For package and imports, this is the only one to access


==== Package *<<github-com-mariotoffia-goasciidoc-goparser-GoPackage,goparser.GoPackage>>


Package where the `File` resides under. Most of the time
is `Package` and `File` the same since rendering is done
on package level.


==== Module *<<github-com-mariotoffia-goasciidoc-goparser-GoModule,goparser.GoModule>>


Module for the context


==== Struct *<<github-com-mariotoffia-goasciidoc-goparser-GoStruct,goparser.GoStruct>>


Struct is the current GoStruct


==== Function *<<github-com-mariotoffia-goasciidoc-goparser-GoStructMethod,goparser.GoStructMethod>>


Function is the current function


==== Interface *<<github-com-mariotoffia-goasciidoc-goparser-GoInterface,goparser.GoInterface>>


Interface is the current GoInterface


==== TypeDefVar *<<github-com-mariotoffia-goasciidoc-goparser-GoCustomType,goparser.GoCustomType>>


TypeDefVar is current variable type definition


==== TypeDefFunc *<<github-com-mariotoffia-goasciidoc-goparser-GoMethod,goparser.GoMethod>>


TypedefFun is current function type definition.


==== VarAssignment *<<github-com-mariotoffia-goasciidoc-goparser-GoAssignment,goparser.GoAssignment>>


VarAssignment is current variable assignment using var keyword


==== ConstAssignment *<<github-com-mariotoffia-goasciidoc-goparser-GoAssignment,goparser.GoAssignment>>


ConstAssignment is current const definition and value assignment


==== Config *<<github-com-mariotoffia-goasciidoc-asciidoc-TemplateContextConfig,TemplateContextConfig>>


Config contains the configuration of this context.


==== Index *<<github-com-mariotoffia-goasciidoc-asciidoc-IndexConfig,IndexConfig>>


Index is configuration to render the index template


==== Receiver []*<<github-com-mariotoffia-goasciidoc-goparser-GoStructMethod,goparser.GoStructMethod>>


Receiver is the current receivers to be rendered.


==== Docs map[string]string


Docs is a map that contains filepaths to various asciidoc documents
that can be included.

.Available Documents
|===
|Name |Comment

|package-overview
|This is a absolute path to a overview document for the current package.

|===



==== Receivers

===== Clone
[source, go]
----
func (t *TemplateContext) Clone(clean bool) *TemplateContext
----
Clone will clone the context.


===== DefaultIndexConfig
[source, go]
----
func (t *TemplateContext) DefaultIndexConfig(overrides string) *IndexConfig
----
DefaultIndexConfig creates a default index configuration that may be used in RenderIndex
function.

The overrides are specifies as a json document, only properties set in the JSON document will
override default IndexConfig.


===== Creator
[source, go]
----
func (t *TemplateContext) Creator() *Template
----
Creator returns the template created this context.


===== RenderPrivate
[source, go]
----
func (t *TemplateContext) RenderPrivate() *TemplateContext
----
RenderPrivate will enable non exported to be rendered.


===== RenderPackage
[source, go]
----
func (t *TemplateContext) RenderPackage(wr io.Writer) *TemplateContext
----
RenderPackage will render the package defintion onto the provided writer.

Depending on if a package overview asciidoc document is found it will prioritize that before
the go package documentation. Hence it will use either _PackageTemplate_ or
_PackageIncludeOverviewTemplate_ depending if found a ascii doc overview document.


===== RenderImports
[source, go]
----
func (t *TemplateContext) RenderImports(wr io.Writer) *TemplateContext
----
RenderImports will render the imports section onto the provided writer.


===== RenderFunctions
[source, go]
----
func (t *TemplateContext) RenderFunctions(wr io.Writer) *TemplateContext
----
RenderFunctions will render all functions for GoFile/GoPackage onto the provided writer.


===== RenderReceiverFunctions
[source, go]
----
func (t *TemplateContext) RenderReceiverFunctions(wr io.Writer, receiver string) *TemplateContext
----
RenderReceiverFunctions will render all receiver functions for a given receiver, albeit a custom type or a struct.


===== RenderFunction
[source, go]
----
func (t *TemplateContext) RenderFunction(wr io.Writer, f *goparser.GoStructMethod) *TemplateContext
----
RenderFunction will render a single function section onto the provided writer.


===== RenderInterfaces
[source, go]
----
func (t *TemplateContext) RenderInterfaces(wr io.Writer) *TemplateContext
----
RenderInterfaces will render all interfaces for GoFile/GoPackage onto the provided writer.


===== RenderInterface
[source, go]
----
func (t *TemplateContext) RenderInterface(wr io.Writer, i *goparser.GoInterface) *TemplateContext
----
RenderInterface will render a single interface section onto the provided writer.


===== RenderStructs
[source, go]
----
func (t *TemplateContext) RenderStructs(wr io.Writer) *TemplateContext
----
RenderStructs will render all structs for GoFile/GoPackage onto the provided writer.


===== RenderStruct
[source, go]
----
func (t *TemplateContext) RenderStruct(wr io.Writer, s *goparser.GoStruct) *TemplateContext
----
RenderStruct will render a single struct section onto the provided writer.


===== RenderVarTypeDefs
[source, go]
----
func (t *TemplateContext) RenderVarTypeDefs(wr io.Writer) *TemplateContext
----
RenderVarTypeDefs will render all variable type definitions for GoFile/GoPackage onto the provided writer.


===== RenderVarTypeDef
[source, go]
----
func (t *TemplateContext) RenderVarTypeDef(wr io.Writer, td *goparser.GoCustomType) *TemplateContext
----
RenderVarTypeDef will render a single variable typedef section onto the provided writer.


===== RenderVarDeclarations
[source, go]
----
func (t *TemplateContext) RenderVarDeclarations(wr io.Writer) *TemplateContext
----
RenderVarDeclarations will render all variable declarations for GoFile/GoPackage onto the provided writer.


===== RenderVarDeclaration
[source, go]
----
func (t *TemplateContext) RenderVarDeclaration(wr io.Writer, a *goparser.GoAssignment) *TemplateContext
----
RenderVarDeclaration will render a single variable declaration section onto the provided writer.


===== RenderConstDeclarations
[source, go]
----
func (t *TemplateContext) RenderConstDeclarations(wr io.Writer) *TemplateContext
----
RenderConstDeclarations will render all const declarations for GoFile/GoPackage onto the provided writer.


===== RenderConstDeclaration
[source, go]
----
func (t *TemplateContext) RenderConstDeclaration(wr io.Writer, a *goparser.GoAssignment) *TemplateContext
----
RenderConstDeclaration will render a single const declaration section onto the provided writer.


===== RenderTypeDefFuncs
[source, go]
----
func (t *TemplateContext) RenderTypeDefFuncs(wr io.Writer) *TemplateContext
----
RenderTypeDefFuncs will render all type definitions for GoFile/GoPackage onto the provided writer.


===== RenderTypeDefFunc
[source, go]
----
func (t *TemplateContext) RenderTypeDefFunc(wr io.Writer, td *goparser.GoMethod) *TemplateContext
----
RenderTypeDefFunc will render a single typedef section onto the provided writer.


===== RenderIndex
[source, go]
----
func (t *TemplateContext) RenderIndex(wr io.Writer, ic *IndexConfig) *TemplateContext
----
RenderIndex will render the complete index page for all GoFiles/GoPackages onto the provided writer.

If nil is provided as IndexConfig it will use the default config.




[[github-com-mariotoffia-goasciidoc-asciidoc-TemplateContextConfig]]

=== TemplateContextConfig
[source, go]
----
type TemplateContextConfig struct {
    IncludeMethodCode       bool
    PackageOverviewPaths    []string
    Private                 bool
    TypeLinks               TypeLinkMode
    SignatureStyle          string
    RenderOptions           map[string]bool
}
----

TemplateContextConfig contains configuration parameters how templates
renders the content and the TemplateContexts behaves.



==== IncludeMethodCode bool


IncludeMethodCode determines if the code is included in the documentation or not.
Default not included.


==== PackageOverviewPaths []string


PackageOverviewPaths paths to search for package overview relative the package path.

It searches the order as they appear in this array until found, then terminates. It is
not possible to have two _*.adoc_ inclusions.

.Example Paths
|===
|Example |Comment

|overview.adoc
|This expects the overview.adoc to be in the same folders as the other go files in the package.

|_design/package-summary.adoc
|This tells the renderer to look for _package-summary.adoc_ in _package path/_design_ folder.

|===


==== Private bool


Private indicates if it shall include private as well. By default only Exported is rendered.


==== TypeLinks <<github-com-mariotoffia-goasciidoc-asciidoc-TypeLinkMode,TypeLinkMode>>


TypeLinks determines how type references are rendered.


==== SignatureStyle string


SignatureStyle determines how signatures are rendered (e.g. "goasciidoc" or "source").


==== RenderOptions map[string]bool


RenderOptions controls what examples to render (struct-json, struct-yaml).





[[github-com-mariotoffia-goasciidoc-asciidoc-IndexConfig]]

=== IndexConfig
[source, go]
----
type IndexConfig struct {
    Title          string
    Version        string
    AuthorName     string
    AuthorEmail    string
    Highlighter    string
    TocTitle       string
    TocLevels      int
    ImageDir       string
    HomePage       string
    DocType        string
}
----

IndexConfig is configuration to use when generating index template



==== JSON Example
[source, json]
----
{
  "title": "example",
  "version": "example",
  "author": "example",
  "email": "example",
  "highlight": "example",
  "toc": "example",
  "toclevel": 0,
  "images": "example",
  "web": "example",
  "doctype": "example"
}
----


==== Title string


Title is the title of the index document, if omitted it uses the module name (if present)


==== Version string


Version is the version stamped as version attribute, if omitted it uses module version (if any)


==== AuthorName string


AuthorName is the full name of the author e.g. Mario Toffia (if none is set, default to current user)


==== AuthorEmail string


AuthorEmail is the email of the author e.g. mario.toffia@bullen.se


==== Highlighter string


Highlighter is the source highlighter to use - default is 'none'


==== TocTitle string


TocTitle is the title of the generated table of contents (if set a toc is generated)
Default is 'Table of Contents', hence by default a TOC is generated.


==== TocLevels int


TocLevels determines how many levels shall it include, default 3


==== ImageDir string


A fully qualified or relative output path to where to search for images


==== HomePage string


HomePage is the url to homepage


==== DocType string


DocType determines the document type, default is book






== Variable Typedefinitions

[[github-com-mariotoffia-goasciidoc-asciidoc-TypeLinkMode]]

=== TypeLinkMode
[source, go]
----
type TypeLinkMode int
----





[[github-com-mariotoffia-goasciidoc-asciidoc-SignatureKind]]

=== SignatureKind
[source, go]
----
type SignatureKind int
----





[[github-com-mariotoffia-goasciidoc-asciidoc-SignatureSegmentKind]]

=== SignatureSegmentKind
[source, go]
----
type SignatureSegmentKind int
----





[[github-com-mariotoffia-goasciidoc-asciidoc-TemplateType]]

=== TemplateType
[source, go]
----
type TemplateType string
----

TemplateType specifies the template type

==== Receivers

===== String
[source, go]
----
func (tt TemplateType) String() string
----





=== Constants
[source, go]
----
const (
    TypeLinksDisabled             TypeLinkMode = 0
    TypeLinksInternal             TypeLinkMode = 1
    TypeLinksInternalExternal     TypeLinkMode = 2
    SignatureKindUnknown          SignatureKind = 0
    SignatureKindFunction         SignatureKind = 1
    SignatureKindMethod           SignatureKind = 2
    SignatureKindFuncType         SignatureKind = 3
    SegmentKindText               SignatureSegmentKind = 0
    SegmentKindKeyword            SignatureSegmentKind = 1
    SegmentKindName               SignatureSegmentKind = 2
    SegmentKindParams             SignatureSegmentKind = 3
    SegmentKindReceiver           SignatureSegmentKind = 4
    SegmentKindResult             SignatureSegmentKind = 5
    SegmentKindTypeName           SignatureSegmentKind = 6
    IndexTemplate                 TemplateType = "index"
    PackageTemplate               TemplateType = "package"
    ImportTemplate                TemplateType = "import"
    FunctionsTemplate             TemplateType = "functions"
    FunctionTemplate              TemplateType = "function"
    InterfacesTemplate            TemplateType = "interfaces"
    InterfaceTemplate             TemplateType = "interface"
    StructsTemplate               TemplateType = "structs"
    StructTemplate                TemplateType = "struct"
    CustomVarTypeDefsTemplate     TemplateType = "typedefvars"
    CustomVarTypeDefTemplate      TemplateType = "typedefvar"
    CustomFuncTypeDefsTemplate    TemplateType = "typedeffuncs"
    CustomFuncTypeDefTemplate     TemplateType = "typedeffunc"
    VarDeclarationsTemplate       TemplateType = "vars"
    VarDeclarationTemplate        TemplateType = "var"
    ConstDeclarationsTemplate     TemplateType = "consts"
    ConstDeclarationTemplate      TemplateType = "const"
    ReceiversTemplate             TemplateType = "receivers"
)
----

=== TypeLinksDisabled
[source, go]
----
TypeLinksDisabled TypeLinkMode = 0
----



=== TypeLinksInternal
[source, go]
----
TypeLinksInternal TypeLinkMode = 1
----



=== TypeLinksInternalExternal
[source, go]
----
TypeLinksInternalExternal TypeLinkMode = 2
----



=== SignatureKindUnknown
[source, go]
----
SignatureKindUnknown SignatureKind = 0
----



=== SignatureKindFunction
[source, go]
----
SignatureKindFunction SignatureKind = 1
----



=== SignatureKindMethod
[source, go]
----
SignatureKindMethod SignatureKind = 2
----



=== SignatureKindFuncType
[source, go]
----
SignatureKindFuncType SignatureKind = 3
----



=== SegmentKindText
[source, go]
----
SegmentKindText SignatureSegmentKind = 0
----



=== SegmentKindKeyword
[source, go]
----
SegmentKindKeyword SignatureSegmentKind = 1
----



=== SegmentKindName
[source, go]
----
SegmentKindName SignatureSegmentKind = 2
----



=== SegmentKindParams
[source, go]
----
SegmentKindParams SignatureSegmentKind = 3
----



=== SegmentKindReceiver
[source, go]
----
SegmentKindReceiver SignatureSegmentKind = 4
----



=== SegmentKindResult
[source, go]
----
SegmentKindResult SignatureSegmentKind = 5
----



=== SegmentKindTypeName
[source, go]
----
SegmentKindTypeName SignatureSegmentKind = 6
----



=== IndexTemplate
[source, go]
----
IndexTemplate TemplateType = "index"
----
IndexTemplate is a template that binds all generated asciidoc files into one single index file
by referencing (or appending to this file).


=== PackageTemplate
[source, go]
----
PackageTemplate TemplateType = "package"
----
PackageTemplate specifies that the template is a package


=== ImportTemplate
[source, go]
----
ImportTemplate TemplateType = "import"
----
ImportTemplate specifies that the template renders a import


=== FunctionsTemplate
[source, go]
----
FunctionsTemplate TemplateType = "functions"
----
FunctionsTemplate is a template to render all functions for a given context (package, file)


=== FunctionTemplate
[source, go]
----
FunctionTemplate TemplateType = "function"
----
FunctionTemplate is a template to render a function


=== InterfacesTemplate
[source, go]
----
InterfacesTemplate TemplateType = "interfaces"
----
InterfacesTemplate is a template to render a all interface defintions for a given context (package, file)


=== InterfaceTemplate
[source, go]
----
InterfaceTemplate TemplateType = "interface"
----
InterfaceTemplate is a template to render a interface definition


=== StructsTemplate
[source, go]
----
StructsTemplate TemplateType = "structs"
----
StructsTemplate specifies that the template renders all struct definitions for a given context (package, file)


=== StructTemplate
[source, go]
----
StructTemplate TemplateType = "struct"
----
StructTemplate specifies that the template renders a struct definition


=== CustomVarTypeDefsTemplate
[source, go]
----
CustomVarTypeDefsTemplate TemplateType = "typedefvars"
----
CustomVarTypeDefsTemplate is a template to render all variable type definitions for a given context (package, file)


=== CustomVarTypeDefTemplate
[source, go]
----
CustomVarTypeDefTemplate TemplateType = "typedefvar"
----
CustomVarTypeDefTemplate is a template to render a type definition of a variable


=== CustomFuncTypeDefsTemplate
[source, go]
----
CustomFuncTypeDefsTemplate TemplateType = "typedeffuncs"
----
CustomFuncTypeDefsTemplate is a template to render all function type definitions for a given context (package, file)


=== CustomFuncTypeDefTemplate
[source, go]
----
CustomFuncTypeDefTemplate TemplateType = "typedeffunc"
----
CustomFuncTypeDefTemplate is a template to render a function type definition


=== VarDeclarationsTemplate
[source, go]
----
VarDeclarationsTemplate TemplateType = "vars"
----
VarDeclarationsTemplate is a template to render all variable definitions for a given context (package, file)


=== VarDeclarationTemplate
[source, go]
----
VarDeclarationTemplate TemplateType = "var"
----
VarDeclarationTemplate is a template to render a variable definition


=== ConstDeclarationsTemplate
[source, go]
----
ConstDeclarationsTemplate TemplateType = "consts"
----
ConstDeclarationsTemplate is a template to render all const declaration entries for a given context (package, file)


=== ConstDeclarationTemplate
[source, go]
----
ConstDeclarationTemplate TemplateType = "const"
----
ConstDeclarationTemplate is a template to render a const declaration entry


=== ReceiversTemplate
[source, go]
----
ReceiversTemplate TemplateType = "receivers"
----
ReceiversTemplate is a template that renders receivers functions


== Variables



== Functions





=== TestTypeSetItemsDeduplicatesAndTrims
[source, go]
----
func TestTypeSetItemsDeduplicatesAndTrims(t *testing.T)
----









=== TestFieldSummaryLinksInternalType
[source, go]
----
func TestFieldSummaryLinksInternalType(t *testing.T)
----








=== TestFieldSummaryExternalTypeLink
[source, go]
----
func TestFieldSummaryExternalTypeLink(t *testing.T)
----








=== TestFieldSummaryDisabled
[source, go]
----
func TestFieldSummaryDisabled(t *testing.T)
----








=== TestFunctionSignatureLinksReceiversAndParams
[source, go]
----
func TestFunctionSignatureLinksReceiversAndParams(t *testing.T)
----








=== TestFunctionSignatureLeavesTypeParameters
[source, go]
----
func TestFunctionSignatureLeavesTypeParameters(t *testing.T)
----








=== TestFunctionSignatureHTMLLinks
[source, go]
----
func TestFunctionSignatureHTMLLinks(t *testing.T)
----








=== TestMethodSignatureHTML
[source, go]
----
func TestMethodSignatureHTML(t *testing.T)
----








=== TestFuncTypeSignatureHTML
[source, go]
----
func TestFuncTypeSignatureHTML(t *testing.T)
----























































=== NewProducer
[source, go]
----
func NewProducer() *Producer
----





NewProducer creates a new instance of a producer.



























=== TestProducerGenerateGolden
[source, go]
----
func TestProducerGenerateGolden(t *testing.T)
----














=== NewTemplateWithOverrides
[source, go]
----
func NewTemplateWithOverrides(overrides map[string]string) *Template
----





NewTemplateWithOverrides creates a new template with the ability to easily
override defaults.







=== TestFunctionDocExampleSpacing
[source, go]
----
func TestFunctionDocExampleSpacing(t *testing.T)
----








=== TestRenderingIncludesTypeParametersAndTypeSets
[source, go]
----
func TestRenderingIncludesTypeParametersAndTypeSets(t *testing.T)
----








=== TestInterfaceWithoutTypeSetOmitsSection
[source, go]
----
func TestInterfaceWithoutTypeSetOmitsSection(t *testing.T)
----











=== TestInterfaceMethodHeadingPlainWithSpacing
[source, go]
----
func TestInterfaceMethodHeadingPlainWithSpacing(t *testing.T)
----


































== Package github.com/mariotoffia/goasciidoc/goparser

Package goparser was taken from an open source project (https://github.com/zpatrick/go-parser) by zpatrick. Since it seemed
that he had abandon it, I've integrated it into this project (and extended it).

=== Imports
[source, go]
----
import (
    "bytes"
    "errors"
    "fmt"
    "os"
    "reflect"
    "runtime"
    "sort"
    "strings"
    "sync"
    "testing"
    "time"
    "unicode"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "go/ast"
    "go/importer"
    "go/parser"
    "go/token"
    "go/types"
    "golang.org/x/mod/modfile"
    "golang.org/x/tools/go/packages"
    "io/ioutil"
    "path/filepath"
)
----

== Interfaces

[[github-com-mariotoffia-goasciidoc-goparser-Resolver]]

=== Resolver
[source, go]
----
type Resolver interface {
    LoadAll() ([]*GoPackage,    error)
}
----



==== Undocumented


[cols="1,1",options="header"]
|===
|Name |Signature
|`LoadAll`|`LoadAll() ([]*GoPackage, error)`
|===



== Structs

[[github-com-mariotoffia-goasciidoc-goparser-GoFile]]

=== GoFile
[source, go]
----
type GoFile struct {
    Module              *GoModule
    Package             string
    FqPackage           string
    FilePath            string
    Doc                 string
    Decl                string
    ImportFullDecl      string
    Structs             []*GoStruct
    Interfaces          []*GoInterface
    Imports             []*GoImport
    StructMethods       []*GoStructMethod
    CustomTypes         []*GoCustomType
    CustomFuncs         []*GoMethod
    VarAssignments      []*GoAssignment
    ConstAssignments    []*GoAssignment
}
----

GoFile represents a complete file



==== Undocumented


[cols="1,1,1",options="header"]
|===
|Field |Type |Tag
|`Module`|`*GoModule`|
|`FilePath`|`string`|
|`Doc`|`string`|
|`Decl`|`string`|
|`ImportFullDecl`|`string`|
|`Structs`|`[]*GoStruct`|
|`Interfaces`|`[]*GoInterface`|
|`Imports`|`[]*GoImport`|
|`StructMethods`|`[]*GoStructMethod`|
|`CustomTypes`|`[]*GoCustomType`|
|`CustomFuncs`|`[]*GoMethod`|
|`VarAssignments`|`[]*GoAssignment`|
|`ConstAssignments`|`[]*GoAssignment`|
|===
==== Package string


Package is the single package name where as FqPackage is the
fully qualified package (if Module) has been set.


==== FqPackage string


FqPackage is the fully qualified package name (if Module field)
is set to calculate the fq package name



==== Receivers

===== FindMethodsByReceiver
[source, go]
----
func (g *GoFile) FindMethodsByReceiver(receiver string) []*GoStructMethod
----
FindMethodsByReceiver searches the file / package after struct and custom type receiver
methods that matches the _receiver_ name.


===== ImportPath
[source, go]
----
func (g *GoFile) ImportPath() (string, error)
----
ImportPath resolves the import path.


===== DeclImports
[source, go]
----
func (g *GoFile) DeclImports() string
----
DeclImports emits the imports




[[github-com-mariotoffia-goasciidoc-goparser-GoImport]]

=== GoImport
[source, go]
----
type GoImport struct {
    File    *GoFile
    Doc     string
    Name    string
    Path    string
}
----

GoImport represents a import of a package



==== Undocumented


[cols="1,1,1",options="header"]
|===
|Field |Type |Tag
|`File`|`*GoFile`|
|`Doc`|`string`|
|`Name`|`string`|
|`Path`|`string`|
|===

==== Receivers

===== Prefix
[source, go]
----
func (g *GoImport) Prefix() string
----
Prefix is for an import - guess what prefix will be used
in type declarations.  For examples:
   "strings" -> "strings"
   "net/http/httptest" -> "httptest"
Libraries where the package name does not match
will be mis-identified.




[[github-com-mariotoffia-goasciidoc-goparser-GoStructMethod]]

=== GoStructMethod
[source, go]
----
type GoStructMethod struct {
    GoMethod
    Receivers        []string
    ReceiverTypes    []*GoType
}
----

GoStructMethod is a GoMethod but has receivers and is positioned on a struct or custom type.



==== Undocumented


[cols="1,1,1",options="header"]
|===
|Field |Type |Tag
|`GoMethod`|`GoMethod`|
|`Receivers`|`[]string`|
|`ReceiverTypes`|`[]*GoType`|
|===



[[github-com-mariotoffia-goasciidoc-goparser-GoMethod]]

=== GoMethod
[source, go]
----
type GoMethod struct {
    File          *GoFile
    Name          string
    Doc           string
    Decl          string
    FullDecl      string
    Exported      bool
    Params        []*GoType
    Results       []*GoType
    TypeParams    []*GoType
}
----

GoMethod is a method on a struct, custom type, interface or just plain function



==== Undocumented


[cols="1,1,1",options="header"]
|===
|Field |Type |Tag
|`File`|`*GoFile`|
|`Name`|`string`|
|`Doc`|`string`|
|`Decl`|`string`|
|`FullDecl`|`string`|
|`Exported`|`bool`|
|`Params`|`[]*GoType`|
|`Results`|`[]*GoType`|
|`TypeParams`|`[]*GoType`|
|===



[[github-com-mariotoffia-goasciidoc-goparser-UnresolvedDecl]]

=== UnresolvedDecl
[source, go]
----
type UnresolvedDecl struct {
    Expr       ast.Expr
    Message    string
}
----



==== Undocumented


[cols="1,1,1",options="header"]
|===
|Field |Type |Tag
|`Expr`|`ast.Expr`|
|`Message`|`string`|
|===



[[github-com-mariotoffia-goasciidoc-goparser-GoModule]]

=== GoModule
[source, go]
----
type GoModule struct {
    File          *modfile.File
    FilePath      string
    Base          string
    Name          string
    Version       string
    GoVersion     string
    Unresolved    []UnresolvedDecl
}
----

GoModule is a simple representation of a go.mod



==== File *link:https://pkg.go.dev/golang.org/x/mod/modfile#File[modfile.File]


File is the actual parsed go.mod file


==== FilePath string


FilePath is the filepath to the go module


==== Base string


Base is where all other packages are relative to.

This is usually the directory to the File field since
go.mod is usually in root project folder.


==== Name string


Name of the module e.g. github.com/mariotoffia/goasciidoc


==== Version string


Version of this module


==== GoVersion string


GoVersion specifies the required go version


==== Unresolved []<<github-com-mariotoffia-goasciidoc-goparser-UnresolvedDecl,UnresolvedDecl>>


UnresolvedDecl contains all unresolved declarations.



==== Receivers

===== AddUnresolvedDeclaration
[source, go]
----
func (gm *GoModule) AddUnresolvedDeclaration(u UnresolvedDecl) *GoModule
----


===== ResolvePackage
[source, go]
----
func (gm *GoModule) ResolvePackage(path string) (string, error)
----
ResolvePackage tries to resolve the full package import path for the provided file path.
When the file resides outside of the module or the module lacks sufficient information,
an error is returned describing the problem.




[[github-com-mariotoffia-goasciidoc-goparser-GoPackage]]

=== GoPackage
[source, go]
----
type GoPackage struct {
    GoFile
    Files    []*GoFile
}
----

GoPackage is a aggregation of all GoFiles in a single
package for ease of access.



==== Undocumented


[cols="1,1,1",options="header"]
|===
|Field |Type |Tag
|`GoFile`|`GoFile`|
|===
==== Files []*<<github-com-mariotoffia-goasciidoc-goparser-GoFile,GoFile>>


Files are all files in current package.





[[github-com-mariotoffia-goasciidoc-goparser-GoTag]]

=== GoTag
[source, go]
----
type GoTag struct {
    File     *GoFile
    Field    *GoField
    Value    string
}
----

GoTag is a tag on a struct field



==== Undocumented


[cols="1,1,1",options="header"]
|===
|Field |Type |Tag
|`File`|`*GoFile`|
|`Field`|`*GoField`|
|`Value`|`string`|
|===

==== Receivers

===== Get
[source, go]
----
func (g *GoTag) Get(key string) string
----
Get returns a struct tag with the specified name e.g. json








[[github-com-mariotoffia-goasciidoc-goparser-ParseConfig]]

=== ParseConfig
[source, go]
----
type ParseConfig struct {
    Test                bool
    Internal            bool
    UnderScore          bool
    Module              *GoModule
    Debug               DebugFunc
    DocConcatenation    DocConcatenationMode
}
----



==== Test bool


Test denotes if test files (ending with _test.go) should be included or not
(default not included)


==== Internal bool


Internal determines if internal folders are included or not (default not)


==== UnderScore bool


UnderScore, when set to true it will include directories beginning with _


==== Module *<<github-com-mariotoffia-goasciidoc-goparser-GoModule,GoModule>>


Optional module to resolve fully qualified package paths


==== Debug <<github-com-mariotoffia-goasciidoc-goparser-DebugFunc,DebugFunc>>


Debug collects debug statements during traversal.


==== DocConcatenation <<github-com-mariotoffia-goasciidoc-goparser-DocConcatenationMode,DocConcatenationMode>>


DocConcatenation controls how doc comments split by blank lines are handled.





[[github-com-mariotoffia-goasciidoc-goparser-ResolverImpl]]

=== ResolverImpl
[source, go]
----
type ResolverImpl struct {
}
----

ResolverImpl is the implementation of a `Resolver` where it operarates on
a `GoModule` level.




==== Receivers

===== LoadAll
[source, go]
----
func (r *ResolverImpl) LoadAll() ([]*GoPackage, error)
----




[[github-com-mariotoffia-goasciidoc-goparser-GoAssignment]]

=== GoAssignment
[source, go]
----
type GoAssignment struct {
    File        *GoFile
    Name        string
    Doc         string
    Decl        string
    FullDecl    string
    Exported    bool
}
----

GoAssignment represents a single var assignment e.g. var pelle = 10



==== Undocumented


[cols="1,1,1",options="header"]
|===
|Field |Type |Tag
|`File`|`*GoFile`|
|`Name`|`string`|
|`Doc`|`string`|
|`FullDecl`|`string`|
|`Exported`|`bool`|
|===
==== Decl string


Decl will be the same if multi var assignment on same row e.g. var pelle, lisa = 10, 19
then both pelle and list will have 'var pelle, lisa = 10, 19' as Decl





[[github-com-mariotoffia-goasciidoc-goparser-GoCustomType]]

=== GoCustomType
[source, go]
----
type GoCustomType struct {
    File          *GoFile
    Name          string
    Doc           string
    Type          string
    Decl          string
    Exported      bool
    TypeParams    []*GoType
}
----

GoCustomType is a custom type definition



==== Undocumented


[cols="1,1,1",options="header"]
|===
|Field |Type |Tag
|`File`|`*GoFile`|
|`Name`|`string`|
|`Doc`|`string`|
|`Type`|`string`|
|`Decl`|`string`|
|`Exported`|`bool`|
|`TypeParams`|`[]*GoType`|
|===



[[github-com-mariotoffia-goasciidoc-goparser-GoInterface]]

=== GoInterface
[source, go]
----
type GoInterface struct {
    File           *GoFile
    Doc            string
    Decl           string
    FullDecl       string
    Name           string
    Exported       bool
    Methods        []*GoMethod
    TypeParams     []*GoType
    TypeSet        []*GoType
    TypeSetDecl    []string
}
----

GoInterface specifies a interface definition



==== Undocumented


[cols="1,1,1",options="header"]
|===
|Field |Type |Tag
|`File`|`*GoFile`|
|`Doc`|`string`|
|`Decl`|`string`|
|`FullDecl`|`string`|
|`Name`|`string`|
|`Exported`|`bool`|
|`Methods`|`[]*GoMethod`|
|`TypeParams`|`[]*GoType`|
|`TypeSet`|`[]*GoType`|
|`TypeSetDecl`|`[]string`|
|===



[[github-com-mariotoffia-goasciidoc-goparser-GoType]]

=== GoType
[source, go]
----
type GoType struct {
    File          *GoFile
    Name          string
    Type          string
    Underlying    string
    Exported      bool
    Inner         []*GoType
    Kind          TypeKind
}
----

GoType represents a go type such as a array, map, custom type etc.



==== Undocumented


[cols="1,1,1",options="header"]
|===
|Field |Type |Tag
|`File`|`*GoFile`|
|`Name`|`string`|
|`Type`|`string`|
|`Underlying`|`string`|
|`Exported`|`bool`|
|`Inner`|`[]*GoType`|
|`Kind`|`TypeKind`|
|===



[[github-com-mariotoffia-goasciidoc-goparser-GoStruct]]

=== GoStruct
[source, go]
----
type GoStruct struct {
    File          *GoFile
    Doc           string
    Decl          string
    FullDecl      string
    Name          string
    Exported      bool
    Fields        []*GoField
    TypeParams    []*GoType
}
----

GoStruct represents a struct



==== Undocumented


[cols="1,1,1",options="header"]
|===
|Field |Type |Tag
|`File`|`*GoFile`|
|`Doc`|`string`|
|`Decl`|`string`|
|`FullDecl`|`string`|
|`Name`|`string`|
|`Exported`|`bool`|
|`Fields`|`[]*GoField`|
|`TypeParams`|`[]*GoType`|
|===

==== Receivers

===== HasJSONTag
[source, go]
----
func (s *GoStruct) HasJSONTag() bool
----
HasJSONTag returns true if any field in the struct has a json tag


===== HasYAMLTag
[source, go]
----
func (s *GoStruct) HasYAMLTag() bool
----
HasYAMLTag returns true if any field in the struct has a yaml tag


===== ToJSON
[source, go]
----
func (s *GoStruct) ToJSON() string
----
ToJSON generates an example JSON representation of the struct


===== ToYAML
[source, go]
----
func (s *GoStruct) ToYAML() string
----
ToYAML generates an example YAML representation of the struct




[[github-com-mariotoffia-goasciidoc-goparser-GoField]]

=== GoField
[source, go]
----
type GoField struct {
    File               *GoFile
    Struct             *GoStruct
    Doc                string
    Decl               string
    Name               string
    Type               string
    Exported           bool
    Tag                *GoTag
    AnonymousStruct    *GoStruct
    TypeInfo           *GoType
}
----

GoField is a field in a file or struct



==== Undocumented


[cols="1,1,1",options="header"]
|===
|Field |Type |Tag
|`File`|`*GoFile`|
|`Struct`|`*GoStruct`|
|`Doc`|`string`|
|`Decl`|`string`|
|`Name`|`string`|
|`Type`|`string`|
|`Exported`|`bool`|
|`Tag`|`*GoTag`|
|`AnonymousStruct`|`*GoStruct`|
|`TypeInfo`|`*GoType`|
|===




== Variable Typedefinitions

[[github-com-mariotoffia-goasciidoc-goparser-DocConcatenationMode]]

=== DocConcatenationMode
[source, go]
----
type DocConcatenationMode int
----

ParseConfig to use when invoking ParseAny, ParseSingleFileWalker, and
ParseSinglePackageWalker.

.ParserConfig
[source,go]
----
include::/Users/solo/progs/github/goasciidoc/goparser/parser.go[tag=parse-config,indent=0]
----
<1> These are usually excluded since many testcases is not documented anyhow
<2> As of _go 1.16_ it is recommended to *only* use module based parsing



[[github-com-mariotoffia-goasciidoc-goparser-TypeKind]]

=== TypeKind
[source, go]
----
type TypeKind int
----

TypeKind represents the general classification of a Go type expression.




=== Constants
[source, go]
----
const (
    DocConcatenationNone    DocConcatenationMode = 0
    DocConcatenationFull    DocConcatenationMode = 1
    TypeKindUnknown         TypeKind = 0
    TypeKindIdent           TypeKind = 1
    TypeKindSelector        TypeKind = 2
    TypeKindPointer         TypeKind = 3
    TypeKindArray           TypeKind = 4
    TypeKindSlice           TypeKind = 5
    TypeKindMap             TypeKind = 6
    TypeKindChan            TypeKind = 7
    TypeKindFunc            TypeKind = 8
    TypeKindStruct          TypeKind = 9
    TypeKindInterface       TypeKind = 10
    TypeKindEllipsis        TypeKind = 11
    TypeKindIndex           TypeKind = 12
    TypeKindIndexList       TypeKind = 13
    TypeKindBinaryExpr      TypeKind = 14
    TypeKindParen           TypeKind = 15
)
----

=== DocConcatenationNone
[source, go]
----
DocConcatenationNone DocConcatenationMode = 0
----



=== DocConcatenationFull
[source, go]
----
DocConcatenationFull DocConcatenationMode = 1
----



=== TypeKindUnknown
[source, go]
----
TypeKindUnknown TypeKind = 0
----



=== TypeKindIdent
[source, go]
----
TypeKindIdent TypeKind = 1
----



=== TypeKindSelector
[source, go]
----
TypeKindSelector TypeKind = 2
----



=== TypeKindPointer
[source, go]
----
TypeKindPointer TypeKind = 3
----



=== TypeKindArray
[source, go]
----
TypeKindArray TypeKind = 4
----



=== TypeKindSlice
[source, go]
----
TypeKindSlice TypeKind = 5
----



=== TypeKindMap
[source, go]
----
TypeKindMap TypeKind = 6
----



=== TypeKindChan
[source, go]
----
TypeKindChan TypeKind = 7
----



=== TypeKindFunc
[source, go]
----
TypeKindFunc TypeKind = 8
----



=== TypeKindStruct
[source, go]
----
TypeKindStruct TypeKind = 9
----



=== TypeKindInterface
[source, go]
----
TypeKindInterface TypeKind = 10
----



=== TypeKindEllipsis
[source, go]
----
TypeKindEllipsis TypeKind = 11
----



=== TypeKindIndex
[source, go]
----
TypeKindIndex TypeKind = 12
----



=== TypeKindIndexList
[source, go]
----
TypeKindIndexList TypeKind = 13
----



=== TypeKindBinaryExpr
[source, go]
----
TypeKindBinaryExpr TypeKind = 14
----



=== TypeKindParen
[source, go]
----
TypeKindParen TypeKind = 15
----



== Function Definitions


[[github-com-mariotoffia-goasciidoc-goparser-DebugFunc]]

=== DebugFunc
[source, go]
----
type DebugFunc func(format string, args ...interface{})
----






[[github-com-mariotoffia-goasciidoc-goparser-ParseSingleFileWalkerFunc]]

=== ParseSingleFileWalkerFunc
[source, go]
----
type ParseSingleFileWalkerFunc func(*GoFile) error
----



ParseSingleFileWalkerFunc is used in conjunction with ParseSingleFileWalker.

If the ParseSingleFileWalker is returning an error, parsing will immediately stop
and the error is returned.


[[github-com-mariotoffia-goasciidoc-goparser-ParseSinglePackageWalkerFunc]]

=== ParseSinglePackageWalkerFunc
[source, go]
----
type ParseSinglePackageWalkerFunc func(*GoPackage) error
----



ParseSinglePackageWalkerFunc is used in conjunction with ParseSinglePackageWalker.

If the ParseSinglePackageWalker is returning an error, parsing will immediately stop
and the error is returned.


== Variables

=== ErrModuleNotConfigured
[source, go]
----
ErrModuleNotConfigured  = errors.New("module not configured")
----



=== ErrPackageOutsideModule
[source, go]
----
ErrPackageOutsideModule = errors.New("path does not belong to module")
----



=== ErrModuleNotFound
[source, go]
----
ErrModuleNotFound       = errors.New("no go.mod found in parent directories")
----










== Functions

=== TestParseSingleFilePreservesDocComments
[source, go]
----
func TestParseSingleFilePreservesDocComments(t *testing.T)
----








=== TestParseHandlesArrayLengthIdentifier
[source, go]
----
func TestParseHandlesArrayLengthIdentifier(t *testing.T)
----








=== TestRenderTypeNameSupportsCompositeTypes
[source, go]
----
func TestRenderTypeNameSupportsCompositeTypes(t *testing.T)
----








=== TestParseSingleFileDoesNotPanicWhenModuleNil
[source, go]
----
func TestParseSingleFileDoesNotPanicWhenModuleNil(t *testing.T)
----








=== TestGetFilePathsSkipsInternalByDefault
[source, go]
----
func TestGetFilePathsSkipsInternalByDefault(t *testing.T)
----








=== TestFindMethodsByReceiverHandlesTypeParameters
[source, go]
----
func TestFindMethodsByReceiverHandlesTypeParameters(t *testing.T)
----








=== TestImportPathUsesModuleInformation
[source, go]
----
func TestImportPathUsesModuleInformation(t *testing.T)
----








=== TestImportPathAutoDetectsModule
[source, go]
----
func TestImportPathAutoDetectsModule(t *testing.T)
----








=== TestImportPathReturnsHelpfulErrorWithoutModule
[source, go]
----
func TestImportPathReturnsHelpfulErrorWithoutModule(t *testing.T)
----








=== TestGenericTypeMetadataCaptured
[source, go]
----
func TestGenericTypeMetadataCaptured(t *testing.T)
----








=== TestInterfaceNestedTypeSet
[source, go]
----
func TestInterfaceNestedTypeSet(t *testing.T)
----









=== FormatTypeParams
[source, go]
----
func FormatTypeParams(params []*GoType) string
----





FormatTypeParams returns the textual representation of a list of type parameters.
For example, `[T any, U ~string]` or an empty string when there are no type parameters.




=== NameWithTypeParams
[source, go]
----
func NameWithTypeParams(name string, params []*GoType) string
----





NameWithTypeParams returns the identifier including formatted type parameters.









=== TestImportBaseShallComeFirst
[source, go]
----
func TestImportBaseShallComeFirst(t *testing.T)
----












=== NewModule
[source, go]
----
func NewModule(path string) (*GoModule, error)
----





NewModule creates a new module from go.mod pointed out in the
in param path parameter.




=== NewModuleFromBuff
[source, go]
----
func NewModuleFromBuff(path string, buff []byte) (*GoModule, error)
----





NewModuleFromBuff creates a new module from the buff specified in
the buff parameter and states that the buff is read from path.




=== FindModule
[source, go]
----
func FindModule(path string) (*GoModule, error)
----





FindModule walks parent directories of the provided path until it locates a go.mod file.
It returns ErrModuleNotFound when no module file is present.





=== TestModuleBasePathIsTakenFromPathParam
[source, go]
----
func TestModuleBasePathIsTakenFromPathParam(t *testing.T)
----








=== TestParseWithOnlyModuleLine
[source, go]
----
func TestParseWithOnlyModuleLine(t *testing.T)
----








=== TestParseWithNoModuleLineMustFail
[source, go]
----
func TestParseWithNoModuleLineMustFail(t *testing.T)
----








=== TestParseModuleNameGoVersionAndRequires
[source, go]
----
func TestParseModuleNameGoVersionAndRequires(t *testing.T)
----





































=== TestIsExportedNormalization
[source, go]
----
func TestIsExportedNormalization(t *testing.T)
----








=== TestBuildVarAssignmentUsesValueSpecSourceWhenNoDoc
[source, go]
----
func TestBuildVarAssignmentUsesValueSpecSourceWhenNoDoc(t *testing.T)
----








=== TestIssue15
[source, go]
----
func TestIssue15(t *testing.T)
----





Issue15 is a bug that notes that ArrayType is not implemented
`not-implemented typeSpec.Type.(type) = *ast.ArrayType`.






















=== ParseSingleFile
[source, go]
----
func ParseSingleFile(mod *GoModule, path string) (*GoFile, error)
----





ParseSingleFile parses a single file at the same time

If a module is passed, it will calculate package relative to that





=== ParseFiles
[source, go]
----
func ParseFiles(mod *GoModule, paths ...string) ([]*GoFile, error)
----





ParseFiles parses one or more files








=== ParseInlineFile
[source, go]
----
func ParseInlineFile(mod *GoModule, path string, code string) (*GoFile, error)
----





ParseInlineFile will parse the code provided.

To simulate package names set the path to some level
equal to or greater than GoModule.Base. Otherwise just
set path "" to ignore.




=== ParseInlineFileWithConfig
[source, go]
----
func ParseInlineFileWithConfig(config ParseConfig, path string, code string) (*GoFile, error)
----








=== ParseAny
[source, go]
----
func ParseAny(config ParseConfig, paths ...string) ([]*GoFile, error)
----





ParseAny parses one or more directories (recursively) for go files. It is also possible
to add files along with directories (or just files).

It is possible to use relative paths or fully qualified paths along with '.'
for current directory. The paths are stat:ed so it will check if it is a file
or directory and do accordingly. If file it will ignore configuration and blindly
accept the file.

The example below parses from current directory down recursively and skips
test, internal and underscore directories.
Example: ParseAny(ParseConfig{}, ".")

Next example will recursively add go files from src and one single test.go under
directory dummy (both relative current directory).
Example: ParseAny(ParseConfig{}, "./src", "./dummy/test.go")




=== ParseSingleFileWalker
[source, go]
----
func ParseSingleFileWalker(config ParseConfig, process ParseSingleFileWalkerFunc, paths ...string) error
----





ParseSingleFileWalker is same as ParseAny, except that it will be fed one GoFile at the
time and thus consume much less memory.

It uses GetFilePaths and hence, the traversal is in sorted order, directory by directory.




=== ParseSinglePackageWalker
[source, go]
----
func ParseSinglePackageWalker(config ParseConfig, process ParseSinglePackageWalkerFunc, paths ...string) error
----





ParseSinglePackageWalker is same as ParseAny, except that it will be fed one GoPackage at the
time and thus consume much less memory.

It uses GetFilePaths and hence, the traversal is in sorted order, directory by directory. It will
bundle all files in same directory and assign those to a GoPackage before invoking ParseSinglePackageWalkerFunc




=== GetFilePaths
[source, go]
----
func GetFilePaths(config ParseConfig, paths ...string) ([]string, error)
----





GetFilePaths will iterate directories (recursively) and add explicit files
in the paths.

It is possible to use relative paths or fully qualified paths along with '.'
for current directory. The paths are stat:ed so it will check if it is a file
or directory and do accordingly. If file it will ignore configuration and blindly
accept the file.




=== TestDocConcatenationModes
[source, go]
----
func TestDocConcatenationModes(t *testing.T)
----








=== TestStructWithSingleGenericArgument
[source, go]
----
func TestStructWithSingleGenericArgument(t *testing.T)
----








=== TestStructWithSingleGenericArgumentAndSimpleReceiverMethod
[source, go]
----
func TestStructWithSingleGenericArgumentAndSimpleReceiverMethod(t *testing.T)
----









=== TestParsePackageDoc
[source, go]
----
func TestParsePackageDoc(t *testing.T)
----








=== TestParseImportDoc
[source, go]
----
func TestParseImportDoc(t *testing.T)
----








=== TestParsePrivateFunction
[source, go]
----
func TestParsePrivateFunction(t *testing.T)
----








=== TestParseExportedFunction
[source, go]
----
func TestParseExportedFunction(t *testing.T)
----








=== TestParseMultilineCppStyleComment
[source, go]
----
func TestParseMultilineCppStyleComment(t *testing.T)
----








=== TestParseMultilineCStyleComment
[source, go]
----
func TestParseMultilineCStyleComment(t *testing.T)
----








=== TestInterfaceDefinitionComment
[source, go]
----
func TestInterfaceDefinitionComment(t *testing.T)
----








=== TestInterfaceMethodComment
[source, go]
----
func TestInterfaceMethodComment(t *testing.T)
----








=== TestStructDefinitionComment
[source, go]
----
func TestStructDefinitionComment(t *testing.T)
----








=== TestStructFieldComment
[source, go]
----
func TestStructFieldComment(t *testing.T)
----








=== TestNestedAnonymousStructDefinitionComment
[source, go]
----
func TestNestedAnonymousStructDefinitionComment(t *testing.T)
----








=== TestNestedStructDefinitionComment
[source, go]
----
func TestNestedStructDefinitionComment(t *testing.T)
----








=== TestCustomTypePrimitive
[source, go]
----
func TestCustomTypePrimitive(t *testing.T)
----








=== TestCustomTypeStructType
[source, go]
----
func TestCustomTypeStructType(t *testing.T)
----








=== TestCustomFunctionDefinition
[source, go]
----
func TestCustomFunctionDefinition(t *testing.T)
----








=== TestSingleLineMultiVarDeclaration
[source, go]
----
func TestSingleLineMultiVarDeclaration(t *testing.T)
----








=== TestPrimitiveConst
[source, go]
----
func TestPrimitiveConst(t *testing.T)
----








=== TestMultiplePrimitiveConst
[source, go]
----
func TestMultiplePrimitiveConst(t *testing.T)
----








=== TestCustomTypeConst
[source, go]
----
func TestCustomTypeConst(t *testing.T)
----








=== TestConstIotaExpansion
[source, go]
----
func TestConstIotaExpansion(t *testing.T)
----








=== TestConstIotaMixedExpressions
[source, go]
----
func TestConstIotaMixedExpressions(t *testing.T)
----








=== TestStructEmbeddedFieldsAndTags
[source, go]
----
func TestStructEmbeddedFieldsAndTags(t *testing.T)
----








=== TestTypeAliasVariants
[source, go]
----
func TestTypeAliasVariants(t *testing.T)
----








=== TestCustomFuncTypeCapturesVariadicParameters
[source, go]
----
func TestCustomFuncTypeCapturesVariadicParameters(t *testing.T)
----








=== TestTypeInfoPopulatesUnderlyingTypes
[source, go]
----
func TestTypeInfoPopulatesUnderlyingTypes(t *testing.T)
----








=== TestExportDetectionNormalizesCompositeTypes
[source, go]
----
func TestExportDetectionNormalizesCompositeTypes(t *testing.T)
----








=== TestParseSingleFileWalkerMatchesParseFilesDocs
[source, go]
----
func TestParseSingleFileWalkerMatchesParseFilesDocs(t *testing.T)
----








=== TestVarInsideCodeIsDiscarded
[source, go]
----
func TestVarInsideCodeIsDiscarded(t *testing.T)
----








=== TestParseStructFunction
[source, go]
----
func TestParseStructFunction(t *testing.T)
----








=== TestFunctionBoundToStruct
[source, go]
----
func TestFunctionBoundToStruct(t *testing.T)
----








=== TestMapStringString
[source, go]
----
func TestMapStringString(t *testing.T)
----








=== TestSingleImportWithAliasShallRenderAliasAndImport
[source, go]
----
func TestSingleImportWithAliasShallRenderAliasAndImport(t *testing.T)
----








=== TestMultipleImportWithAliasShallRenderAliasAndImport
[source, go]
----
func TestMultipleImportWithAliasShallRenderAliasAndImport(t *testing.T)
----








=== TestMultipleImportWithAliasAndNonAliasShallRenderAliasAndImportOnCorrectPlaces
[source, go]
----
func TestMultipleImportWithAliasAndNonAliasShallRenderAliasAndImportOnCorrectPlaces(t *testing.T)
----








=== TestMultipleImportShallRenderImports
[source, go]
----
func TestMultipleImportShallRenderImports(t *testing.T)
----








=== TestSingleImportShallRenderImport
[source, go]
----
func TestSingleImportShallRenderImport(t *testing.T)
----








=== TestCustomArray
[source, go]
----
func TestCustomArray(t *testing.T)
----








=== TestCustomSlicePtr
[source, go]
----
func TestCustomSlicePtr(t *testing.T)
----








=== NewResolver
[source, go]
----
func NewResolver(config ParseConfig, filepath string) Resolver
----





NewResolver creates a new `Resolver` from the filepath to the _go.mod_ file
or directory where _go.mod_ resides.






=== TestPackageAggregationSharedBetweenWalkerAndResolver
[source, go]
----
func TestPackageAggregationSharedBetweenWalkerAndResolver(t *testing.T)
----






















=== TestHasJSONTag
[source, go]
----
func TestHasJSONTag(t *testing.T)
----








=== TestHasYAMLTag
[source, go]
----
func TestHasYAMLTag(t *testing.T)
----








=== TestToJSON
[source, go]
----
func TestToJSON(t *testing.T)
----








=== TestToYAML
[source, go]
----
func TestToYAML(t *testing.T)
----










== Package github.com/mariotoffia/goasciidoc/internal/utils



=== Imports
[source, go]
----
import (
    "fmt"
    "io"
    "os"
    "io/ioutil"
    "path/filepath"
)
----

== Functions

=== CopyFile
[source, go]
----
func CopyFile(src string, dst string) err error
----





CopyFile copies the contents of the file named src to the file named
by dst. The file will be created if it does not already exist. If the
destination file exists, all it's contents will be replaced by the contents
of the source file. The file mode will be copied from the source and
the copied data is synced/flushed to stable storage.




=== TempCopyDir
[source, go]
----
func TempCopyDir(src string, prefix string) (string, error)
----





TempCopyDir will copy the src directory recursively onto a newly created
temporary directory. If succeeds it returns the temp directory for use.

use defer os.RemoveAll(tmpdir) when done to cleanup.




=== CopyDir
[source, go]
----
func CopyDir(src string, dst string, exists bool) err error
----





CopyDir recursively copies a directory tree, attempting to preserve permissions.
Source directory must exist, destination directory must *not* exist.
Symlinks are ignored and skipped.

If exists is set to true, it won't fail if dst already exists.





