= github.com/mariotoffia/goasciidoc
:author_name: martoffi
:author: {author_name}
:source-highlighter: highlightjs
:icons: font
:kroki-default-format: svg
:doctype: book

== package asciidoc

=== Imports
[source, go]
----
import (
        "io"
        "io/ioutil"
        "os"
        "path/filepath"
        "strings"
        "github.com/mariotoffia/goasciidoc/goparser"
        "text/tabwriter"
        "bytes"
        "text/template"
        "encoding/json"
        "os/user"
)
----

== Structs
=== Producer
[source, go]
----
type Producer struct {
        parseconfig        goparser.ParseConfig
        paths              []string
        outfile            string
        index              bool
        indexconfig        string
        overrides          map[string]string
        writer             io.Writer
}
----
                
Producer parses go code and produces asciidoc documentation.

==== parseconfig goparser.ParseConfig
parseconfig is the configuration that it uses to invoke
the parser with.

==== paths []string
paths is files and directories to include.

==== outfile string
outfile is the file to write the generated documentation onto

==== index bool
index determines if it will render index as header for all
rendered documents. If inclusion, this might be a good idea
not to render index. Default is true.

==== indexconfig string
indexconfig is a JSON document to override the default IndexConfig
when rendering the index template

==== overrides map[string]string
overrides is the template overrides that is passed to the template engine.

==== writer io.Writer
writer is a fixed custom writer that *all* gets written to.

=== writer
[source, go]
----
type writer struct {
        w        io.Writer
}
----
                


==== w io.Writer


=== Template
[source, go]
----
type Template struct {
        Templates        map[string]*template.Template
}
----
                
Template is handling all templates and actions
to perform.

==== Templates map[string]*template.Template
Templates to use when rendering documentation

=== TemplateContext
[source, go]
----
type TemplateContext struct {
        creator                *Template
        File                   *goparser.GoFile
        Module                 *goparser.GoModule
        Struct                 *goparser.GoStruct
        Function               *goparser.GoStructMethod
        Interface              *goparser.GoInterface
        TypeDefVar             *goparser.GoCustomType
        TypeDefFunc            *goparser.GoMethod
        VarAssignment          *goparser.GoAssignment
        ConstAssignment        *goparser.GoAssignment
        Config                 *TemplateContextConfig
        Index                  *IndexConfig
}
----
                
TemplateContext is a context that may be used to render
a GoFile. Depending on the template, different fields are
populated in this struct.

==== creator *Template
creator is the template created this context.

==== File *goparser.GoFile
File is the complete file. This property is always present.

For package and imports, this is the only one to access

==== Module *goparser.GoModule
Module for the context

==== Struct *goparser.GoStruct
Struct is the current GoStruct

==== Function *goparser.GoStructMethod
Function is the current function

==== Interface *goparser.GoInterface
Interface is the current GoInterface

==== TypeDefVar *goparser.GoCustomType
TypeDefVar is current variable type definition

==== TypeDefFunc *goparser.GoMethod
TypedefFun is current function type defintion.

==== VarAssignment *goparser.GoAssignment
VarAssignment is current variable assignment using var keyword

==== ConstAssignment *goparser.GoAssignment
ConstAssignment is current const definition and value assignment

==== Config *TemplateContextConfig
Config contains the configuration of this context.

==== Index *IndexConfig
Index is configuration to render the index template

=== TemplateContextConfig
[source, go]
----
type TemplateContextConfig struct {
        IncludeMethodCode        bool
}
----
                
TemplateContextConfig contains configuration parameters how templates
renders the content and the TemplateContexts behaves.

==== IncludeMethodCode bool
IncludeMethodCode determines if the code is included in the documentation or not.
Default not included.

=== IndexConfig
[source, go]
----
type IndexConfig struct {
        Title              string
        Version            string
        AuthorName         string
        AuthorEmail        string
        Highlighter        string
        TocTitle           string
        TocLevels          int
        ImageDir           string
        HomePage           string
        DocType            string
}
----
                
IndexConfig is configuration to use when generating index template

==== Title string
Title is the title of the index document, if omitted it uses the module name (if present)

==== Version string
Version is the version stamped as version attribute, if omitted it uses module version (if any)

==== AuthorName string
AuthorName is the full name of the author e.g. Mario Toffia (if none is set, default to current user)

==== AuthorEmail string
AuthorEmail is the email of the author e.g. mario.toffia@bullen.se

==== Highlighter string
Highlighter is the source highlighter to use - default is 'highlightjs'

==== TocTitle string
TocTitle is the title of the generated table of contents (if set a toc is generated)

==== TocLevels int
TocLevels determines how many levels shall it include, default 3

==== ImageDir string
A fully qualified or relative output path to where to search for images

==== HomePage string
HomePage is the url to homepage

==== DocType string
DocType determines the document type, default is book


== Variable Typedefinitions
=== TemplateType
[source, go]
----
type TemplateType string
----
TemplateType specifies the template type

=== Constants
[source, go]
----
const (
        IndexTemplate                     TemplateType = "index"
        PackageTemplate                   TemplateType = "package"
        ImportTemplate                    TemplateType = "import"
        FunctionsTemplate                 TemplateType = "functions"
        FunctionTemplate                  TemplateType = "function"
        InterfacesTemplate                TemplateType = "interfaces"
        InterfaceTemplate                 TemplateType = "interface"
        StructsTemplate                   TemplateType = "structs"
        StructTemplate                    TemplateType = "struct"
        CustomVarTypeDefsTemplate         TemplateType = "typedefvars"
        CustomVarTypeDefTemplate          TemplateType = "typedefvar"
        CustomFuncTypeDefsTemplate        TemplateType = "typedeffuncs"
        CustomFuncTypeDefTemplate         TemplateType = "typedeffunc"
        VarDeclarationsTemplate           TemplateType = "vars"
        VarDeclarationTemplate            TemplateType = "var"
        ConstDeclarationsTemplate         TemplateType = "consts"
        ConstDeclarationTemplate          TemplateType = "const"
)
----

=== IndexTemplate
[source, go]
----
IndexTemplate TemplateType = "index"
----
IndexTemplate is a template that binds all generated asciidoc files into one single index file
by referencing (or appending to this file).

=== PackageTemplate
[source, go]
----
PackageTemplate TemplateType = "package"
----
PackageTemplate specifies that the template is a package

=== ImportTemplate
[source, go]
----
ImportTemplate TemplateType = "import"
----
ImportTemplate specifies that the template renders a import

=== FunctionsTemplate
[source, go]
----
FunctionsTemplate TemplateType = "functions"
----
FunctionsTemplate is a template to render all functions for a given context (package, file)

=== FunctionTemplate
[source, go]
----
FunctionTemplate TemplateType = "function"
----
FunctionTemplate is a template to render a function

=== InterfacesTemplate
[source, go]
----
InterfacesTemplate TemplateType = "interfaces"
----
InterfacesTemplate is a template to render a all interface defintions for a given context (package, file)

=== InterfaceTemplate
[source, go]
----
InterfaceTemplate TemplateType = "interface"
----
InterfaceTemplate is a template to render a interface defintion

=== StructsTemplate
[source, go]
----
StructsTemplate TemplateType = "structs"
----
StructsTemplate specifies that the template renders all struct defenitions for a given context (package, file)

=== StructTemplate
[source, go]
----
StructTemplate TemplateType = "struct"
----
StructTemplate specifies that the template renders a struct defenition

=== CustomVarTypeDefsTemplate
[source, go]
----
CustomVarTypeDefsTemplate TemplateType = "typedefvars"
----
CustomVarTypeDefsTemplate is a template to render all variable type definitions for a given context (package, file)

=== CustomVarTypeDefTemplate
[source, go]
----
CustomVarTypeDefTemplate TemplateType = "typedefvar"
----
CustomVarTypeDefTemplate is a template to render a type definition of a variable

=== CustomFuncTypeDefsTemplate
[source, go]
----
CustomFuncTypeDefsTemplate TemplateType = "typedeffuncs"
----
CustomFuncTypeDefsTemplate is a template to render all function type definitions for a given context (package, file)

=== CustomFuncTypeDefTemplate
[source, go]
----
CustomFuncTypeDefTemplate TemplateType = "typedeffunc"
----
CustomFuncTypeDefTemplate is a template to render a function type definition

=== VarDeclarationsTemplate
[source, go]
----
VarDeclarationsTemplate TemplateType = "vars"
----
VarDeclarationsTemplate is a template to render all variable definitions for a given context (package, file)

=== VarDeclarationTemplate
[source, go]
----
VarDeclarationTemplate TemplateType = "var"
----
VarDeclarationTemplate is a template to render a variable definition

=== ConstDeclarationsTemplate
[source, go]
----
ConstDeclarationsTemplate TemplateType = "consts"
----
ConstDeclarationsTemplate is a template to render all const declaration entries for a given context (package, file)

=== ConstDeclarationTemplate
[source, go]
----
ConstDeclarationTemplate TemplateType = "const"
----
ConstDeclarationTemplate is a template to render a const declaration entry

== Variables

=== templateIndex
[source, go]
----
var templateIndex = `= {{ .Index.Title }}
{{- if .Index.AuthorName}}{{cr}}:author_name: {{.Index.AuthorName}}{{cr}}:author: {author_name}{{end}}
{{- if .Index.AuthorEmail}}{{cr}}:author_email: {{.Index.AuthorEmail}}{{cr}}:email: {author_email}{{end}}
:source-highlighter: {{ .Index.Highlighter }}
{{- if .Index.TocTitle}}{{cr}}:toc:{{cr}}:toc-title: {{ .Index.TocTitle }}{{cr}}:toclevels: {{ .Index.TocLevels }}{{end}}
:icons: font
{{- if .Index.ImageDir}}{{cr}}:imagesdir: {{.Index.ImageDir}}{{end}}
{{- if .Index.HomePage}}{{cr}}:homepage: {{.Index.HomePage}}{{end}}
:kroki-default-format: svg
:doctype: {{.Index.DocType}}

`
----


=== templatePackage
[source, go]
----
var templatePackage = `== {{if .File.FqPackage}}package {{.File.FqPackage}}{{else}}{{.File.Decl}}{{end}}
{{ .File.Doc }}
`
----


=== templateImports
[source, go]
----
var templateImports = `=== Imports
[source, go]
----
{{ render . }}
----
{{range .File.Imports}}{{if .Doc }}{{ cr }}==== Import _{{ .Path }}_{{ cr }}{{ .Doc }}{{ cr }}{{end}}{{end}}
`
----


=== templateFunctions
[source, go]
----
var templateFunctions = `== Functions
{{range .File.StructMethods}}
{{- render $ .}}
{{end}}
`
----


=== templateFunction
[source, go]
----
var templateFunction = `=== {{ .Function.Name }}
[source, go]
----
{{ .Function.Decl }}
----

{{ .Function.Doc }}
{{ if .Config.IncludeMethodCode }}{{cr}}[source, go]{{cr}}----{{cr}}{{ .Function.FullDecl }}{{cr}}----{{end}}`
----


=== templateInterface
[source, go]
----
var templateInterface = `=== {{ .Interface.Name }}
[source, go]
----
{{.Interface.Decl}} {
{{- range .Interface.Methods}}
        {{.Decl}}
{{- end}}
}
----
                
{{ .Interface.Doc }}
{{range .Interface.Methods}}
==== {{.Decl}}
{{.Doc}}
{{end}}`
----


=== templateInterfaces
[source, go]
----
var templateInterfaces = `== Interfaces
{{range .File.Interfaces}}
{{- render $ .}}
{{end}}
`
----


=== templateStruct
[source, go]
----
var templateStruct = `=== {{.Struct.Name}}
[source, go]
----
{{.Struct.Decl}} {
{{- range .Struct.Fields}}
        {{tabify .Decl}}
{{- end}}
}
----
                
{{ .Struct.Doc }}
{{range .Struct.Fields}}
==== {{.Decl}}
{{.Doc}}
{{end}}`
----


=== templateStructs
[source, go]
----
var templateStructs = `== Structs
{{range .File.Structs}}
{{- render $ .}}
{{end}}
`
----


=== templateCustomTypeDefintion
[source, go]
----
var templateCustomTypeDefintion = `=== {{.TypeDefVar.Name}}
[source, go]
----
{{.TypeDefVar.Decl}}
----
{{.TypeDefVar.Doc}}`
----


=== templateCustomTypeDefintions
[source, go]
----
var templateCustomTypeDefintions = `== Variable Typedefinitions
{{range .File.CustomTypes}}
{{- render $ .}}
{{end}}
`
----


=== templateVarAssignment
[source, go]
----
var templateVarAssignment = `=== {{.VarAssignment.Name}}
[source, go]
----
{{.VarAssignment.FullDecl}}
----
{{.VarAssignment.Doc}}`
----


=== templateVarAssignments
[source, go]
----
var templateVarAssignments = `== Variables
{{range .File.VarAssigments}}
{{render $ .}}
{{end}}
`
----


=== templateConstAssignment
[source, go]
----
var templateConstAssignment = `=== {{.ConstAssignment.Name}}
[source, go]
----
{{.ConstAssignment.Decl}}
----
{{.ConstAssignment.Doc}}`
----


=== templateConstAssignments
[source, go]
----
var templateConstAssignments = `=== Constants
[source, go]
----
const (
        {{- range .File.ConstAssignments}}
        {{tabify .Decl}}
        {{- end}}
)
----
{{range .File.ConstAssignments}}
{{render $ .}}
{{end}}
`
----


=== templateCustomFuncDefintion
[source, go]
----
var templateCustomFuncDefintion = `=== {{.TypeDefFunc.Name}}
[source, go]
----
{{.TypeDefFunc.Decl}}
----
{{.TypeDefFunc.Doc}}`
----


=== templateCustomFuncDefintions
[source, go]
----
var templateCustomFuncDefintions = `== Function Definitions
{{range .File.CustomFuncs}}
{{render $ .}}
{{end}}
`
----


== Functions
=== NewProducer
[source, go]
----
func NewProducer() *Producer
----

NewProducer creates a new instance of a producer.

=== StdOut
[source, go]
----
func (p *Producer) StdOut() *Producer
----

StdOut writes to stdout instead onto filesystem.

=== Writer
[source, go]
----
func (p *Producer) Writer(w io.Writer) *Producer
----

Writer sets a custom writer where *everything* gets written to.

=== OverrideFilePath
[source, go]
----
func (p *Producer) OverrideFilePath(name, path string) *Producer
----

OverrideFilePath will use another template instead of a built-in default
for the particular name (see TemplateType for valid template names)
This is loaded from the inparam path.

=== Override
[source, go]
----
func (p *Producer) Override(name, template string) *Producer
----

Override will use another template instead of a built-in default
for the particular name (see TemplateType for valid template names)

=== Outfile
[source, go]
----
func (p *Producer) Outfile(path string) *Producer
----

Outfile sets a file to write to

=== NoIndex
[source, go]
----
func (p *Producer) NoIndex(overrides string) *Producer
----

NoIndex specifies that the genereated asciidoctor document will not have
a index header. This is good for inclusion where a header is already present.

=== IndexConfig
[source, go]
----
func (p *Producer) IndexConfig(overrides string) *Producer
----

IndexConfig will configures using SON properties and hence it
will override the default IndexConfig configuration. If no overide,
just pass an empty string.

=== Module
[source, go]
----
func (p *Producer) Module(path string) *Producer
----

Module directs the producer to pick up module from path.

path may be a directory or a full path to go.mod. If "" it
will use current directory.

=== Include
[source, go]
----
func (p *Producer) Include(path ...string) *Producer
----

Include adds one or more directory or files in any combination. The producer
will sort out which are directories and which are filepaths.

If filepath, it will not do any type of checking and will blindly think it is a
valid go file.

=== IncludeTest
[source, go]
----
func (p *Producer) IncludeTest() *Producer
----

IncludeTest will create documentation for test files as well.

=== IncludeInternal
[source, go]
----
func (p *Producer) IncludeInternal() *Producer
----

IncludeInternal will include internal folder source files.

=== IncludeUnderScoreDirectories
[source, go]
----
func (p *Producer) IncludeUnderScoreDirectories() *Producer
----

IncludeUnderScoreDirectories will include files that resides below
directories starting with underscore.

=== Generate
[source, go]
----
func (p *Producer) Generate()
----

Generate will execute the generation of the documentation

=== createWriter
[source, go]
----
func (p *Producer) createWriter() io.Writer
----



=== dirExists
[source, go]
----
func dirExists(dir string) bool
----



=== String
[source, go]
----
func (tt TemplateType) String() string
----



=== NewTemplate
[source, go]
----
func NewTemplate() *Template
----

NewTemplate creates a new set of templates to be used

=== NewTemplateWithOverrides
[source, go]
----
func NewTemplateWithOverrides(overrides map[string]string) *Template
----

NewTemplateWithOverrides creates a new template with the ability to easily
override defaults.

=== NewContext
[source, go]
----
func (t *Template) NewContext(f *goparser.GoFile) *TemplateContext
----

NewContext creates a new context to be used for rendering.

=== NewContextWithConfig
[source, go]
----
func (t *Template) NewContextWithConfig(f *goparser.GoFile, config *TemplateContextConfig) *TemplateContext
----

NewContextWithConfig creates a new context with configuration.

If configuration is nil, it will use default configuration.

=== createTemplate
[source, go]
----
func createTemplate(name TemplateType, str string, overrides map[string]string, fm template.FuncMap) *template.Template
----

createTemplate will create a template named name and parses the str
as template. If fails it will panic with the parse error.

If name is found in override map it will use that string to parse the template
instead of the provided str.

=== Clone
[source, go]
----
func (t *TemplateContext) Clone(clean bool) *TemplateContext
----

Clone will clone the context.

=== DefaultIndexConfig
[source, go]
----
func (t *TemplateContext) DefaultIndexConfig(overrides string) *IndexConfig
----

DefaultIndexConfig creates a default index configuration that may be used in RenderIndex
function.

The overrides are specifies as a json document, only properties set in the JSON document will
override default IndexConfig.

=== Creator
[source, go]
----
func (t *TemplateContext) Creator() *Template
----

Creator returns the template created this context.

=== RenderPackage
[source, go]
----
func (t *TemplateContext) RenderPackage(wr io.Writer) *TemplateContext
----

RenderPackage will render the package defintion onto the provided writer.

=== RenderImports
[source, go]
----
func (t *TemplateContext) RenderImports(wr io.Writer) *TemplateContext
----

RenderImports will render the imports section onto the provided writer.

=== RenderFunctions
[source, go]
----
func (t *TemplateContext) RenderFunctions(wr io.Writer) *TemplateContext
----

RenderFunctions will render all functions for GoFile/GoPackage onto the provided writer.

=== RenderFunction
[source, go]
----
func (t *TemplateContext) RenderFunction(wr io.Writer, f *goparser.GoStructMethod) *TemplateContext
----

RenderFunction will render a single function section onto the provided writer.

=== RenderInterfaces
[source, go]
----
func (t *TemplateContext) RenderInterfaces(wr io.Writer) *TemplateContext
----

RenderInterfaces will render all interfaces for GoFile/GoPackage onto the provided writer.

=== RenderInterface
[source, go]
----
func (t *TemplateContext) RenderInterface(wr io.Writer, i *goparser.GoInterface) *TemplateContext
----

RenderInterface will render a single interface section onto the provided writer.

=== RenderStructs
[source, go]
----
func (t *TemplateContext) RenderStructs(wr io.Writer) *TemplateContext
----

RenderStructs will render all structs for GoFile/GoPackage onto the provided writer.

=== RenderStruct
[source, go]
----
func (t *TemplateContext) RenderStruct(wr io.Writer, s *goparser.GoStruct) *TemplateContext
----

RenderStruct will render a single struct section onto the provided writer.

=== RenderVarTypeDefs
[source, go]
----
func (t *TemplateContext) RenderVarTypeDefs(wr io.Writer) *TemplateContext
----

RenderVarTypeDefs will render all variable type definitions for GoFile/GoPackage onto the provided writer.

=== RenderVarTypeDef
[source, go]
----
func (t *TemplateContext) RenderVarTypeDef(wr io.Writer, td *goparser.GoCustomType) *TemplateContext
----

RenderVarTypeDef will render a single variable typedef section onto the provided writer.

=== RenderVarDeclarations
[source, go]
----
func (t *TemplateContext) RenderVarDeclarations(wr io.Writer) *TemplateContext
----

RenderVarDeclarations will render all variable declarations for GoFile/GoPackage onto the provided writer.

=== RenderVarDeclaration
[source, go]
----
func (t *TemplateContext) RenderVarDeclaration(wr io.Writer, a *goparser.GoAssignment) *TemplateContext
----

RenderVarDeclaration will render a single variable declaration section onto the provided writer.

=== RenderConstDeclarations
[source, go]
----
func (t *TemplateContext) RenderConstDeclarations(wr io.Writer) *TemplateContext
----

RenderConstDeclarations will render all const declarations for GoFile/GoPackage onto the provided writer.

=== RenderConstDeclaration
[source, go]
----
func (t *TemplateContext) RenderConstDeclaration(wr io.Writer, a *goparser.GoAssignment) *TemplateContext
----

RenderConstDeclaration will render a single const declaration section onto the provided writer.

=== RenderTypeDefFuncs
[source, go]
----
func (t *TemplateContext) RenderTypeDefFuncs(wr io.Writer) *TemplateContext
----

RenderTypeDefFuncs will render all type definitions for GoFile/GoPackage onto the provided writer.

=== RenderTypeDefFunc
[source, go]
----
func (t *TemplateContext) RenderTypeDefFunc(wr io.Writer, td *goparser.GoMethod) *TemplateContext
----

RenderTypeDefFunc will render a single typedef section onto the provided writer.

=== RenderIndex
[source, go]
----
func (t *TemplateContext) RenderIndex(wr io.Writer, ic *IndexConfig) *TemplateContext
----

RenderIndex will render the complete index page for all GoFiles/GoPackages onto the provided writer.

If nil is provided as IndexConfig it will use the default config.


== package main

== Functions
=== main
[source, go]
----
func main()
----




== package goparser
Package goparser was taken from an open source project (https://github.com/zpatrick/go-parser) by zpatrick. Since it seemed
that he had abandon it, I've integrated it into this project (and extended it).

=== Imports
[source, go]
----
import (
        "fmt"
        "os"
        "path/filepath"
        "strings"
        "io/ioutil"
        "golang.org/x/mod/modfile"
        "reflect"
        "go/ast"
        "go/token"
        "go/types"
        "go/parser"
        "sort"
)
----

== Structs
=== GoFile
[source, go]
----
type GoFile struct {
        Module                  *GoModule
        Package                 string
        FqPackage               string
        FilePath                string
        Doc                     string
        Decl                    string
        ImportFullDecl          string
        Structs                 []*GoStruct
        Interfaces              []*GoInterface
        Imports                 []*GoImport
        StructMethods           []*GoStructMethod
        CustomTypes             []*GoCustomType
        CustomFuncs             []*GoMethod
        VarAssigments           []*GoAssignment
        ConstAssignments        []*GoAssignment
}
----
                
GoFile represents a complete file

==== Module *GoModule


==== Package string
Package is the single package name where as FqPackage is the
fully qualified package (if Module) has been set.

==== FqPackage string
FqPackage is the fully qualified package name (if Module field)
is set to calculate the fq package name

==== FilePath string


==== Doc string


==== Decl string


==== ImportFullDecl string


==== Structs []*GoStruct


==== Interfaces []*GoInterface


==== Imports []*GoImport


==== StructMethods []*GoStructMethod


==== CustomTypes []*GoCustomType


==== CustomFuncs []*GoMethod


==== VarAssigments []*GoAssignment


==== ConstAssignments []*GoAssignment


=== GoImport
[source, go]
----
type GoImport struct {
        File        *GoFile
        Doc         string
        Name        string
        Path        string
}
----
                
GoImport represents a import of a package

==== File *GoFile


==== Doc string


==== Name string


==== Path string


=== GoModule
[source, go]
----
type GoModule struct {
        File             *modfile.File
        FilePath         string
        Base             string
        Name             string
        Version          string
        GoVersion        string
}
----
                
GoModule is a simple representation of a go.mod

==== File *modfile.File
File is the actual parsed go.mod file

==== FilePath string
FilePath is the filepath to the go module

==== Base string
Base is where all other packages are relative to.

This is usually the directory to the File field since
go.mod is usually in root project folder.

==== Name string
Name of the module e.g. github.com/mariotoffia/goasciidoc

==== Version string
Version of this module

==== GoVersion string
GoVersion specifies the required go version

=== GoPackage
[source, go]
----
type GoPackage struct {
        GoFile
        Files        []*GoFile
}
----
                
GoPackage is a aggregation of all GoFiles in a single
package for ease of access.

==== GoFile


==== Files []*GoFile
Files are all files in current package.

=== GoTag
[source, go]
----
type GoTag struct {
        File         *GoFile
        Field        *GoField
        Value        string
}
----
                
GoTag is a tag on a struct field

==== File *GoFile


==== Field *GoField


==== Value string


=== ParseConfig
[source, go]
----
type ParseConfig struct {
        Test              bool
        Internal          bool
        UnderScore        bool
        Module            *GoModule
}
----
                
ParseConfig to use when invoking ParseAny, ParseSingleFileWalker, and
ParseSinglePackageWalker.

==== Test bool
Test denotes if test files (ending with _test.go) should be included or not
(default not included)

==== Internal bool
Internal determines if internal folders are included or not (default not)

==== UnderScore bool
UnderScore, when set to true it will include directories beginning with _

==== Module *GoModule
Optional module to resolve fully qualified package paths

=== GoAssignment
[source, go]
----
type GoAssignment struct {
        File            *GoFile
        Name            string
        Doc             string
        Decl            string
        FullDecl        string
}
----
                
GoAssignment represents a single var assignment e.g. var pelle = 10

==== File *GoFile


==== Name string


==== Doc string


==== Decl string
Decl will be the same if multi var assignment on same row e.g. var pelle, lisa = 10, 19
then both pelle and list will have 'var pelle, lisa = 10, 19' as Decl

==== FullDecl string


=== GoCustomType
[source, go]
----
type GoCustomType struct {
        File        *GoFile
        Name        string
        Doc         string
        Type        string
        Decl        string
}
----
                
GoCustomType is a custom type definition

==== File *GoFile


==== Name string


==== Doc string


==== Type string


==== Decl string


=== GoInterface
[source, go]
----
type GoInterface struct {
        File            *GoFile
        Doc             string
        Decl            string
        FullDecl        string
        Name            string
        Methods         []*GoMethod
}
----
                
GoInterface specifies a interface definition

==== File *GoFile


==== Doc string


==== Decl string


==== FullDecl string


==== Name string


==== Methods []*GoMethod


=== GoMethod
[source, go]
----
type GoMethod struct {
        File            *GoFile
        Name            string
        Doc             string
        Decl            string
        FullDecl        string
        Params          []*GoType
        Results         []*GoType
}
----
                
GoMethod is a method on a struct, interface or just plain function

==== File *GoFile


==== Name string


==== Doc string


==== Decl string


==== FullDecl string


==== Params []*GoType


==== Results []*GoType


=== GoStructMethod
[source, go]
----
type GoStructMethod struct {
        GoMethod
        Receivers        []string
}
----
                
GoStructMethod is a GoMethod but has receivers and is positioned on a struct.

==== GoMethod


==== Receivers []string


=== GoType
[source, go]
----
type GoType struct {
        File              *GoFile
        Name              string
        Type              string
        Underlying        string
        Inner             []*GoType
}
----
                
GoType represents a go type such as a array, map, custom type etc.

==== File *GoFile


==== Name string


==== Type string


==== Underlying string


==== Inner []*GoType


=== GoStruct
[source, go]
----
type GoStruct struct {
        File            *GoFile
        Doc             string
        Decl            string
        FullDecl        string
        Name            string
        Fields          []*GoField
}
----
                
GoStruct represents a struct

==== File *GoFile


==== Doc string


==== Decl string


==== FullDecl string


==== Name string


==== Fields []*GoField


=== GoField
[source, go]
----
type GoField struct {
        File          *GoFile
        Struct        *GoStruct
        Doc           string
        Decl          string
        Name          string
        Type          string
        Tag           *GoTag
}
----
                
GoField is a field in a file or struct

==== File *GoFile


==== Struct *GoStruct


==== Doc string


==== Decl string


==== Name string


==== Type string


==== Tag *GoTag



== Function Definitions

=== ParseSingleFileWalkerFunc
[source, go]
----
type ParseSingleFileWalkerFunc func(*GoFile) error
----
ParseSingleFileWalkerFunc is used in conjuction with ParseSingleFileWalker.

If the ParseSingleFileWalker is returning an error, parsing will immediately stop
and the error is returned.

=== ParseSinglePackageWalkerFunc
[source, go]
----
type ParseSinglePackageWalkerFunc func(*GoPackage) error
----
ParseSinglePackageWalkerFunc is used in conjuction with ParseSinglePackageWalker.

If the ParseSinglePackageWalker is returning an error, parsing will immediately stop
and the error is returned.

== Functions
=== ImportPath
[source, go]
----
func (g *GoFile) ImportPath() (string, error)
----

ImportPath is for TODO:

=== DeclImports
[source, go]
----
func (g *GoFile) DeclImports() string
----

DeclImports emits the imports

=== Prefix
[source, go]
----
func (g *GoImport) Prefix() string
----

Prefix is for an import - guess what prefix will be used
in type declarations.  For examples:
   "strings" -> "strings"
   "net/http/httptest" -> "httptest"
Libraries where the package name does not match
will be mis-identified.

=== ResolvePackage
[source, go]
----
func (gm *GoModule) ResolvePackage(path string) string
----

ResolvePackage wil try to resolve the full package path
bases on this module and the provided path.

If it fails, it returns an empty string.

=== NewModule
[source, go]
----
func NewModule(path string) (*GoModule, error)
----

NewModule creates a new module from go.mod pointed out in the
inparam path parameter.

=== NewModuleFromBuff
[source, go]
----
func NewModuleFromBuff(path string, buff []byte) (*GoModule, error)
----

NewModuleFromBuff creates a new module from the buff specified in
the buff parameter and states that the buff is read from path.

=== Get
[source, go]
----
func (g *GoTag) Get(key string) string
----

Get returns a struct tag with the specified name e.g. json

=== parseFile
[source, go]
----
func parseFile(mod *GoModule, path string, source []byte, file *ast.File, fset *token.FileSet, files []*ast.File) (*GoFile, error)
----



=== buildVarAssignment
[source, go]
----
func buildVarAssignment(file *GoFile, genDecl *ast.GenDecl, valueSpec *ast.ValueSpec, source []byte) []*GoAssignment
----



=== extractDocs
[source, go]
----
func extractDocs(doc *ast.CommentGroup) string
----



=== buildGoImport
[source, go]
----
func buildGoImport(spec *ast.ImportSpec, file *GoFile) *GoImport
----



=== buildGoInterface
[source, go]
----
func buildGoInterface(source []byte, file *GoFile, info *types.Info, typeSpec *ast.TypeSpec, interfaceType *ast.InterfaceType) *GoInterface
----



=== buildMethodList
[source, go]
----
func buildMethodList(file *GoFile, info *types.Info, fieldList []*ast.Field, source []byte) []*GoMethod
----



=== buildStructMethod
[source, go]
----
func buildStructMethod(file *GoFile, info *types.Info, funcDecl *ast.FuncDecl, source []byte) *GoStructMethod
----



=== buildReceiverList
[source, go]
----
func buildReceiverList(info *types.Info, fieldList *ast.FieldList, source []byte) []string
----



=== buildTypeList
[source, go]
----
func buildTypeList(file *GoFile, info *types.Info, fieldList *ast.FieldList, source []byte) []*GoType
----



=== getNames
[source, go]
----
func getNames(field *ast.Field) []string
----



=== getTypeString
[source, go]
----
func getTypeString(expr ast.Expr, source []byte) string
----



=== getUnderlyingTypeString
[source, go]
----
func getUnderlyingTypeString(info *types.Info, expr ast.Expr) string
----



=== copyType
[source, go]
----
func copyType(goType *GoType) *GoType
----



=== buildType
[source, go]
----
func buildType(file *GoFile, info *types.Info, expr ast.Expr, source []byte) *GoType
----



=== buildGoStruct
[source, go]
----
func buildGoStruct(source []byte, file *GoFile, info *types.Info, typeSpec *ast.TypeSpec, structType *ast.StructType) *GoStruct
----



=== ParseSingleFile
[source, go]
----
func ParseSingleFile(mod *GoModule, path string) (*GoFile, error)
----

ParseSingleFile parses a single file at the same time

If a module is passed, it will calculate package relative to that

=== ParseFiles
[source, go]
----
func ParseFiles(mod *GoModule, paths ...string) ([]*GoFile, error)
----

ParseFiles parses one or more files

=== ParseInlineFile
[source, go]
----
func ParseInlineFile(mod *GoModule, path, code string) (*GoFile, error)
----

ParseInlineFile will parse the code provided.

To simulate package names set the path to some level
equal to or greater than GoModule.Base. Otherwise just
set path "" to ignore.

=== ParseAny
[source, go]
----
func ParseAny(config ParseConfig, paths ...string) ([]*GoFile, error)
----

ParseAny parses one or more directories (recursively) for go files. It is also possible
to add files along with directories (or just files).

It is possible to use relative paths or fully qualified paths along with '.'
for current directory. The paths are stat:ed so it will check if it is a file
or directory and do accordingly. If file it will ignore configuration and blindly
accept the file.

The example below parses from current directory down recursively and skips
test, internal and underscore directories.
Example: ParseAny(ParseConfig{}, ".")

Next example will recursively add go files from src and one single test.go under
directory dummy (both relative current directory).
Example: ParseAny(ParseConfig{}, "./src", "./dummy/test.go")

=== ParseSingleFileWalker
[source, go]
----
func ParseSingleFileWalker(config ParseConfig, process ParseSingleFileWalkerFunc, paths ...string) error
----

ParseSingleFileWalker is same as ParseAny, except that it will be fed one GoFile at the
time and thus consume much less memory.

It uses GetFilePaths and hence, the traversal is in sorted order, directory by directory.

=== ParseSinglePackageWalker
[source, go]
----
func ParseSinglePackageWalker(config ParseConfig, process ParseSinglePackageWalkerFunc, paths ...string) error
----

ParseSinglePackageWalker is same as ParseAny, except that it will be fed one GoPackage at the
time and thus consume much less memory.

It uses GetFilePaths and hence, the traversal is in sorted order, directory by directory. It will
bundle all files in same directory and assign those to a GoPackage before invoking ParseSinglePackageWalkerFunc

=== GetFilePaths
[source, go]
----
func GetFilePaths(config ParseConfig, paths ...string) ([]string, error)
----

GetFilePaths will iterate directories (recursively) and add explicit files
in the paths.

It is possible to use relative paths or fully qualified paths along with '.'
for current directory. The paths are stat:ed so it will check if it is a file
or directory and do accordingly. If file it will ignore configuration and blindly
accept the file.
