== Interfaces
=== IInterface
[source, go]
----
type IInterface interface {
	Bar() int
	baz() time.Time
}
----
		
IInterface is a public interface.

==== Bar() int
Bar is a public function that outputs
current time and return zero.

==== baz() time.Time
baz is a private function that returns current time.

=== MyInterface
[source, go]
----
type MyInterface interface {
	FooBot(i IInterface) string
}
----
		
MyInterface is a plain interface to do misc stuff.

==== FooBot(i IInterface) string
FooBot is a public method to do just that! ;)

== Structs
=== Person
[source, go]
----
type Person struct {
	Name string
	Born time.Time
	Age uint8
}
----
		
Person is a public struct describing
a persons name, age and when he or
she was born.

==== Name string
Name is full name

==== Born time.Time
Born is when the person was born

==== Age uint8
Age is how old this person is now

=== Anka
[source, go]
----
type Anka struct {
	Loudness int32
}
----
		
Anka is a duck

==== Loudness int32
Loudness is the amplitude of the kvack!

== Variable Type Definitions

=== MyVarTypeDef
[source, go]
----
type MyVarTypeDef int
----
MyVarTypeDef is a type that wraps a int to a custom type

== Variables

=== MyVar
[source, go]
----
var MyVar int = 99
----
MyVar is a var declaration that is exported

=== dryrun
[source, go]
----
var dryrun = false
----
dryrun determines if the lambda will affect resources or just log

=== Constants
[source, go]
----
const (
	MyConstVar string = "apa"
	NextVar string = "next"
)
----

=== MyConstVar
[source, go]
----
MyConstVar string = "apa"
----
MyConstVar is just to demonstrate a single const declaration

=== NextVar
[source, go]
----
NextVar string = "next"
----
NextVar is more trixy...